### ISSUE TITLE
homepage balance is incorrect

### ISSUE THREAD

**Issue by kirooshii** [dafraer/MoneyBuddy#8]
homepage balance shows -balance (balance * -1):
![image](https://github.com/dafraer/MoneyBuddy/assets/120464003/075643e8-08c2-46b2-8222-b35e4c900646)
![image](https://github.com/dafraer/MoneyBuddy/assets/120464003/fd24fafe-8052-40fd-bc5f-22e2566c0773)

it's not an html problem, because - hasn't appeared there
![image](https://github.com/dafraer/MoneyBuddy/assets/120464003/b02116b7-31a0-40b3-8692-39068c1b0a43)

@dafraer pls check go variable

**Comment by kirooshii** [comment]
**@dafraer is {{.PiggyBank.Balance}} = {{.Balance}}?** 
Maybe it's easier to don't make a piggybank as an additional one..
or then why changes in piggybank affects main account
now i'm not against to cancel piggy bank idea, let's vote

**Comment by dafraer** [comment]
Changes on piggybank affect the main account because money doesnt grow on trees, and when you add money to your piggybank it gets this money from your main account.
